<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="kingkoen1b9a" name="nl.cubix.scrabble.boardimporter.BoardExtracterTest" tests="1" failures="1" timestamp="21 Oct 2011 19:05:47 GMT" time="0.485" errors="0">
  <testcase name="extract" time="0.485" classname="nl.cubix.scrabble.boardimporter.BoardExtracterTest">
    <failure type="java.awt.image.RasterFormatException" message="(x + width) is outside of Raster">
      <![CDATA[java.awt.image.RasterFormatException: (x + width) is outside of Raster
	at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1230)
	at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1156)
	at nl.cubix.scrabble.boardimporter.BoardExtracter.cropAndBlackAndWhite(BoardExtracter.java:223)
	at nl.cubix.scrabble.boardimporter.BoardExtracter.extractBoard(BoardExtracter.java:99)
	at nl.cubix.scrabble.boardimporter.BoardExtracter.extract(BoardExtracter.java:63)
	at nl.cubix.scrabble.boardimporter.BoardExtracterTest.extract(BoardExtracterTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
    </failure>
  </testcase>
</testsuite>
